name: food_delivery
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.11.1+16

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.5
  flutter_mobx: ^2.2.1+1
  nb_utils: ^7.0.0
  onesignal_flutter: ^5.1.4
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^17.0.1
  firebase_messaging: ^14.8.1
  cloud_firestore: ^4.16.1
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.6
  geocoding: ^3.0.0
  google_maps_flutter: ^2.2.8
  geolocator: ^11.0.0
  audioplayers: ^6.0.0
  upgrader: ^10.2.0
  package_info_plus: ^7.0.0
  share: ^2.0.4
  flutter_vector_icons: ^2.0.0
  firebase_auth: ^4.19.1
  google_sign_in: ^6.2.1
  audio_video_progress_bar: ^2.0.2
  firebase_pagination: ^3.1.0
  file_picker: ^8.0.0+1
  firebase_storage: ^11.7.1
  audio_waveforms: ^1.0.5
  chat_bubbles: ^1.5.0
  google_fonts: ^6.2.1
  timeago: ^3.6.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7
  change_app_package_name: ^1.1.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/flag/
    - lang/

