// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIcCd-I5JKJi84dUGWYVRAB5NVpTj0I6A',
    appId: '1:485649260159:android:b9b61c7b3c74819cdde94a',
    messagingSenderId: '485649260159',
    projectId: 'coucouexpress-502d4',
    storageBucket: 'coucouexpress-502d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_WBbBPll7PLZrF9OZORimVKg_QPxSpEI',
    appId: '1:485649260159:ios:559b573253782d92dde94a',
    messagingSenderId: '485649260159',
    projectId: 'coucouexpress-502d4',
    storageBucket: 'coucouexpress-502d4.appspot.com',
    androidClientId: '485649260159-v35tphao1fqnbai7orv74g72om3ukbrl.apps.googleusercontent.com',
    iosClientId: '485649260159-60fe063e3fbe1puqe15j9oudk7vibiho.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDelivery',
  );
}
